# 
# Vagrantfile per i progetti client-server (per esempio, il progetto asw-830-rmi), che prevedono:
# - un nodo server 
# - un nodo db 
# 

VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
    # Configurazioni comuni.

    # Ubuntu trusty 64 VirtualBox.
    config.vm.box = "ubuntu/trusty64"

    # folder per i progetti Asw (/home/vagrant/projects)
    config.vm.synced_folder "../../projects/", "/home/vagrant/projects", :mount_options => ["dmode=777", "fmode=777"]

    # folder per le risorse condivise per gli ambienti Asw (/home/vagrant/shared/resources e /home/vagrant/shared/scripts) 
    config.vm.synced_folder "../shared/", "/home/vagrant/shared", :mount_options => ["dmode=777", "fmode=777"]

    #
    # Configurazione del nodo "db", che prevede: 
    # - Mongo DB
    #
    config.vm.define "db" do |node|
        node.vm.hostname = "db"    
        node.vm.network "private_network", ip: "10.11.1.201", virtualbox__intnet: true

        node.vm.provider "virtualbox" do |v| 
            v.memory = 1024 
        end 

        node.vm.network "forwarded_port", guest: 27017, host: 27017, id: 'mongodb', auto_correct: true
        node.vm.network "forwarded_port", guest: 22, host: 2221, id: 'ssh', auto_correct: true
        node.ssh.forward_agent = true
        
        # provisioning con bash 
        node.vm.provision :shell, :inline => 'apt-get update'
        
        # provisioning 
        node.vm.provision :shell, :inline => 'mkdir -p /data/db'

        # provisioning con chef
        node.vm.provision :chef_solo do |chef|
            chef.cookbooks_path = "../shared/cookbooks"
            chef.add_recipe "mongodb-debs"
        end
        
        node.vm.provision :shell, :inline => 'nohup mongod --bind_ip 10.11.1.201 &'

	 node.vm.provision :shell, :inline => 'sh /home/vagrant/projects/restore.sh'
        
        node.vm.provision :shell, 
            inline: "echo  'configurazione nodo db completata'"

    end

    #
    # Configurazione del nodo "server", che prevede: 
    # - Node JS
    #
    config.vm.define "server" do |node|
        node.vm.hostname = "server"   

        #node.vm.network "public_network", ip: "10.11.1.301"
        node.vm.network "private_network", ip: "10.11.1.101", virtualbox__intnet: true

        node.vm.provider "virtualbox" do |v| 
            v.memory = 1024 
        end 

        node.vm.network "forwarded_port", guest: 3000, host: 8080, id: 'webapp', auto_correct: true
        node.vm.network "forwarded_port", guest: 22, host: 2211, id: 'ssh', auto_correct: true
        node.ssh.forward_agent = true
 
        # provisioning con bash 
        node.vm.provision :shell, :inline => 'apt-get update'
        
        # provisioning con chef
        node.vm.provision :chef_solo do |chef|
            chef.cookbooks_path = "../shared/cookbooks"
            chef.add_recipe "nodejs"            
        end

        #node.vm.provision :shell, :inline => 'cd /home/vagrant/projects/snapcook;npm install;npm start'
        
        #node.vm.provision :shell, :inline =>'nohup npm install &'
        #node.vm.provision :shell, :inline =>'nohup npm start &'
        #node.vm.provision :shell, :inline =>'node projects/snapcook/app.js'
	
	    node.vm.provision :shell, :inline => 'sh /home/vagrant/projects/run.sh'
	
    
        node.vm.provision :shell, 
            inline: "echo  'configurazione nodo server completata'"

    end

end
